apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    app.kubernetes.io/part-of: maelkloud-platform
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: maelkloud-gateway
  namespace: istio-ingress
  labels:
    app.kubernetes.io/part-of: maelkloud-platform
spec:
  gatewayClassName: istio
  listeners:
    - name: stock-public
      hostname: stock-intelligence.maelkloud.com
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway-access: maelkloud
    - name: argocd-public
      hostname: argocd.maelkloud.com
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway-access: maelkloud
