apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock-intelligence
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh: hard
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/xmaeltht/stock-intelligent.git
    targetRevision: main
    path: charts/stock-intelligence
    helm:
      releaseName: stock-intelligence
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stock-intelligence
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
